### ISSUE TITLE
关于McPatch下载时的建议

### ISSUE THREAD

**Issue by Bu7eneChen** [BalloonUpdate/McPatchDocs#5]
我发现mcpatch在更新的时候文件会临时储存在内存里，这会导致部分可用内存较少的玩家下载大的更新包是出现out of memory的报错导致循环下载并且无法成功下载完成。建议把临时文件直接储存在硬盘内

**Comment by asforest** [comment]
v2版本已经是直接写入硬盘的流式传输。v1还不是，但没有适配的计划。

**Comment by Bu7eneChen** [comment]
好的谢谢
